version: '3'
services:
  project:
    build: ./project
    container_name: project
    environment:
      - FLASK_ENV=development
      - PYTHONUNBUFFERED=True
    restart: on-failure
    volumes:
      - ./project:/project
    ports:
      - 3000:3000
    command: python main.py
